// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: docs_lab/dtd_proto/measures.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ch.heigvd.iict.dma.protobuf;

@kotlin.jvm.JvmName("-initializemeasure")
public inline fun measure(block: ch.heigvd.iict.dma.protobuf.MeasureKt.Dsl.() -> kotlin.Unit): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Measure =
  ch.heigvd.iict.dma.protobuf.MeasureKt.Dsl._create(ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Measure.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `Measure`
 */
public object MeasureKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Measure.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Measure.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Measure = _builder.build()

    /**
     * `uint32 id = 1;`
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.id
      @JvmName("setId")
      set(value) {
        _builder.id = value
      }
    /**
     * `uint32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `.Status status = 2;`
     */
    public var status: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Status
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.statusValue
      @JvmName("setStatusValue")
      set(value) {
        _builder.statusValue = value
      }
    /**
     * `.Status status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `string type = 3;`
     */
    public var type: kotlin.String
      @JvmName("getType")
      get() = _builder.type
      @JvmName("setType")
      set(value) {
        _builder.type = value
      }
    /**
     * `string type = 3;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `double value = 4;`
     */
    public var value: kotlin.Double
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * `double value = 4;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }

    /**
     * `uint64 date = 5;`
     */
    public var date: kotlin.Long
      @JvmName("getDate")
      get() = _builder.date
      @JvmName("setDate")
      set(value) {
        _builder.date = value
      }
    /**
     * `uint64 date = 5;`
     */
    public fun clearDate() {
      _builder.clearDate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Measure.copy(block: `ch.heigvd.iict.dma.protobuf`.MeasureKt.Dsl.() -> kotlin.Unit): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Measure =
  `ch.heigvd.iict.dma.protobuf`.MeasureKt.Dsl._create(this.toBuilder()).apply { block() }._build()

