// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: docs_lab/dtd_proto/measures.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ch.heigvd.iict.dma.protobuf;

@kotlin.jvm.JvmName("-initializemeasuresAck")
public inline fun measuresAck(block: ch.heigvd.iict.dma.protobuf.MeasuresAckKt.Dsl.() -> kotlin.Unit): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasuresAck =
  ch.heigvd.iict.dma.protobuf.MeasuresAckKt.Dsl._create(ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasuresAck.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `MeasuresAck`
 */
public object MeasuresAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasuresAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasuresAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasuresAck = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MeasuresProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .MeasureAck measures = 1;`
     */
     public val measures: com.google.protobuf.kotlin.DslList<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck, MeasuresProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.measuresList
      )
    /**
     * `repeated .MeasureAck measures = 1;`
     * @param value The measures to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMeasures")
    public fun com.google.protobuf.kotlin.DslList<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck, MeasuresProxy>.add(value: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck) {
      _builder.addMeasures(value)
    }
    /**
     * `repeated .MeasureAck measures = 1;`
     * @param value The measures to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMeasures")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck, MeasuresProxy>.plusAssign(value: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck) {
      add(value)
    }
    /**
     * `repeated .MeasureAck measures = 1;`
     * @param values The measures to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMeasures")
    public fun com.google.protobuf.kotlin.DslList<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck, MeasuresProxy>.addAll(values: kotlin.collections.Iterable<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck>) {
      _builder.addAllMeasures(values)
    }
    /**
     * `repeated .MeasureAck measures = 1;`
     * @param values The measures to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMeasures")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck, MeasuresProxy>.plusAssign(values: kotlin.collections.Iterable<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck>) {
      addAll(values)
    }
    /**
     * `repeated .MeasureAck measures = 1;`
     * @param index The index to set the value at.
     * @param value The measures to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMeasures")
    public operator fun com.google.protobuf.kotlin.DslList<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck, MeasuresProxy>.set(index: kotlin.Int, value: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck) {
      _builder.setMeasures(index, value)
    }
    /**
     * `repeated .MeasureAck measures = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMeasures")
    public fun com.google.protobuf.kotlin.DslList<ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck, MeasuresProxy>.clear() {
      _builder.clearMeasures()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasuresAck.copy(block: `ch.heigvd.iict.dma.protobuf`.MeasuresAckKt.Dsl.() -> kotlin.Unit): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasuresAck =
  `ch.heigvd.iict.dma.protobuf`.MeasuresAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

